/**
 * Whiteboard templates
 *
 * Each template is a named set of Excalidraw elements. Templates are applied
 * by calling excalidrawAPI.updateScene({ elements }). They intentionally do
 * not reset appState (zoom, scroll position) so the user's current viewport
 * is preserved.
 *
 * Element IDs use a "tmpl-" prefix so loadScene / merge operations can
 * identify them as template-origin elements if needed in the future.
 */

// Element types are kept loose because Excalidraw's internal branded types
// (e.g. lineHeight: number & { _brand: 'unitlessLineHeight' }) cannot be
// constructed from static data without a cast. The elements are passed to
// excalidrawAPI.updateScene() which accepts any-shaped objects at runtime.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AnyElement = Record<string, any>

const NOW = Date.now()

/** A 4-quadrant retrospective layout */
const retroElements: AnyElement[] = [
  // Top-left: Went Well
  {
    id: 'tmpl-retro-tl-bg',
    type: 'rectangle',
    x: -400,
    y: -300,
    width: 380,
    height: 280,
    angle: 0,
    strokeColor: '#2f9e44',
    backgroundColor: '#d3f9d8',
    fillStyle: 'solid',
    strokeWidth: 2,
    strokeStyle: 'solid',
    roughness: 0,
    opacity: 100,
    groupIds: ['retro-tl'],
    roundness: { type: 3 },
    isDeleted: false,
    boundElements: [],
    updated: NOW,
    link: null,
    locked: false,
    frameId: null,
    seed: 1001,
    version: 1,
    versionNonce: 1001,
  } as AnyElement,
  {
    id: 'tmpl-retro-tl-label',
    type: 'text',
    x: -400,
    y: -310,
    width: 380,
    height: 30,
    angle: 0,
    strokeColor: '#2f9e44',
    backgroundColor: 'transparent',
    fillStyle: 'solid',
    strokeWidth: 1,
    strokeStyle: 'solid',
    roughness: 0,
    opacity: 100,
    groupIds: ['retro-tl'],
    roundness: null,
    isDeleted: false,
    boundElements: [],
    updated: NOW,
    link: null,
    locked: false,
    frameId: null,
    seed: 1002,
    version: 1,
    versionNonce: 1002,
    text: 'Went Well',
    fontSize: 20,
    fontFamily: 1,
    textAlign: 'center',
    verticalAlign: 'top',
    containerId: null,
    originalText: 'Went Well',
    lineHeight: 1.25,
    baseline: 18,
  } as AnyElement,
  // Top-right: Needs Improvement
  {
    id: 'tmpl-retro-tr-bg',
    type: 'rectangle',
    x: 20,
    y: -300,
    width: 380,
    height: 280,
    angle: 0,
    strokeColor: '#e67700',
    backgroundColor: '#fff3bf',
    fillStyle: 'solid',
    strokeWidth: 2,
    strokeStyle: 'solid',
    roughness: 0,
    opacity: 100,
    groupIds: ['retro-tr'],
    roundness: { type: 3 },
    isDeleted: false,
    boundElements: [],
    updated: NOW,
    link: null,
    locked: false,
    frameId: null,
    seed: 1003,
    version: 1,
    versionNonce: 1003,
  } as AnyElement,
  {
    id: 'tmpl-retro-tr-label',
    type: 'text',
    x: 20,
    y: -310,
    width: 380,
    height: 30,
    angle: 0,
    strokeColor: '#e67700',
    backgroundColor: 'transparent',
    fillStyle: 'solid',
    strokeWidth: 1,
    strokeStyle: 'solid',
    roughness: 0,
    opacity: 100,
    groupIds: ['retro-tr'],
    roundness: null,
    isDeleted: false,
    boundElements: [],
    updated: NOW,
    link: null,
    locked: false,
    frameId: null,
    seed: 1004,
    version: 1,
    versionNonce: 1004,
    text: 'Needs Improvement',
    fontSize: 20,
    fontFamily: 1,
    textAlign: 'center',
    verticalAlign: 'top',
    containerId: null,
    originalText: 'Needs Improvement',
    lineHeight: 1.25,
    baseline: 18,
  } as AnyElement,
  // Bottom-left: Action Items
  {
    id: 'tmpl-retro-bl-bg',
    type: 'rectangle',
    x: -400,
    y: 0,
    width: 380,
    height: 280,
    angle: 0,
    strokeColor: '#1971c2',
    backgroundColor: '#d0ebff',
    fillStyle: 'solid',
    strokeWidth: 2,
    strokeStyle: 'solid',
    roughness: 0,
    opacity: 100,
    groupIds: ['retro-bl'],
    roundness: { type: 3 },
    isDeleted: false,
    boundElements: [],
    updated: NOW,
    link: null,
    locked: false,
    frameId: null,
    seed: 1005,
    version: 1,
    versionNonce: 1005,
  } as AnyElement,
  {
    id: 'tmpl-retro-bl-label',
    type: 'text',
    x: -400,
    y: -10,
    width: 380,
    height: 30,
    angle: 0,
    strokeColor: '#1971c2',
    backgroundColor: 'transparent',
    fillStyle: 'solid',
    strokeWidth: 1,
    strokeStyle: 'solid',
    roughness: 0,
    opacity: 100,
    groupIds: ['retro-bl'],
    roundness: null,
    isDeleted: false,
    boundElements: [],
    updated: NOW,
    link: null,
    locked: false,
    frameId: null,
    seed: 1006,
    version: 1,
    versionNonce: 1006,
    text: 'Action Items',
    fontSize: 20,
    fontFamily: 1,
    textAlign: 'center',
    verticalAlign: 'top',
    containerId: null,
    originalText: 'Action Items',
    lineHeight: 1.25,
    baseline: 18,
  } as AnyElement,
  // Bottom-right: Risks
  {
    id: 'tmpl-retro-br-bg',
    type: 'rectangle',
    x: 20,
    y: 0,
    width: 380,
    height: 280,
    angle: 0,
    strokeColor: '#c92a2a',
    backgroundColor: '#ffe3e3',
    fillStyle: 'solid',
    strokeWidth: 2,
    strokeStyle: 'solid',
    roughness: 0,
    opacity: 100,
    groupIds: ['retro-br'],
    roundness: { type: 3 },
    isDeleted: false,
    boundElements: [],
    updated: NOW,
    link: null,
    locked: false,
    frameId: null,
    seed: 1007,
    version: 1,
    versionNonce: 1007,
  } as AnyElement,
  {
    id: 'tmpl-retro-br-label',
    type: 'text',
    x: 20,
    y: -10,
    width: 380,
    height: 30,
    angle: 0,
    strokeColor: '#c92a2a',
    backgroundColor: 'transparent',
    fillStyle: 'solid',
    strokeWidth: 1,
    strokeStyle: 'solid',
    roughness: 0,
    opacity: 100,
    groupIds: ['retro-br'],
    roundness: null,
    isDeleted: false,
    boundElements: [],
    updated: NOW,
    link: null,
    locked: false,
    frameId: null,
    seed: 1008,
    version: 1,
    versionNonce: 1008,
    text: 'Risks',
    fontSize: 20,
    fontFamily: 1,
    textAlign: 'center',
    verticalAlign: 'top',
    containerId: null,
    originalText: 'Risks',
    lineHeight: 1.25,
    baseline: 18,
  } as AnyElement,
]

/** A grid of 6 sticky notes for brainstorming */
const brainstormColors = [
  { stroke: '#e67700', bg: '#fff3bf' },
  { stroke: '#2f9e44', bg: '#d3f9d8' },
  { stroke: '#1971c2', bg: '#d0ebff' },
  { stroke: '#c92a2a', bg: '#ffe3e3' },
  { stroke: '#862e9c', bg: '#f3d9fa' },
  { stroke: '#0c8599', bg: '#c5f6fa' },
]

const brainstormElements: AnyElement[] = brainstormColors.flatMap(({ stroke, bg }, i) => {
  const col = i % 3
  const row = Math.floor(i / 3)
  const x = col * 220 - 330
  const y = row * 220 - 120
  const seed = 2000 + i * 10

  return [
    {
      id: `tmpl-sticky-${i}-bg`,
      type: 'rectangle',
      x,
      y,
      width: 200,
      height: 200,
      angle: 0,
      strokeColor: stroke,
      backgroundColor: bg,
      fillStyle: 'solid',
      strokeWidth: 2,
      strokeStyle: 'solid',
      roughness: 1,
      opacity: 100,
      groupIds: [`sticky-${i}`],
      roundness: { type: 3 },
      isDeleted: false,
      boundElements: [],
      updated: NOW,
      link: null,
      locked: false,
      frameId: null,
      seed,
      version: 1,
      versionNonce: seed,
    } as AnyElement,
    {
      id: `tmpl-sticky-${i}-text`,
      type: 'text',
      x: x + 10,
      y: y + 10,
      width: 180,
      height: 30,
      angle: 0,
      strokeColor: stroke,
      backgroundColor: 'transparent',
      fillStyle: 'solid',
      strokeWidth: 1,
      strokeStyle: 'solid',
      roughness: 0,
      opacity: 100,
      groupIds: [`sticky-${i}`],
      roundness: null,
      isDeleted: false,
      boundElements: [],
      updated: NOW,
      link: null,
      locked: false,
      frameId: null,
      seed: seed + 1,
      version: 1,
      versionNonce: seed + 1,
      text: 'Click to add idea...',
      fontSize: 16,
      fontFamily: 1,
      textAlign: 'left',
      verticalAlign: 'top',
      containerId: null,
      originalText: 'Click to add idea...',
      lineHeight: 1.25,
      baseline: 14,
    } as AnyElement,
  ]
})

/** A simple linear flowchart */
const flowchartElements: AnyElement[] = [
  // Start
  {
    id: 'tmpl-flow-start',
    type: 'ellipse',
    x: -100,
    y: -260,
    width: 200,
    height: 60,
    angle: 0,
    strokeColor: '#2f9e44',
    backgroundColor: '#d3f9d8',
    fillStyle: 'solid',
    strokeWidth: 2,
    strokeStyle: 'solid',
    roughness: 0,
    opacity: 100,
    groupIds: [],
    roundness: null,
    isDeleted: false,
    boundElements: [{ id: 'tmpl-flow-a1', type: 'arrow' }],
    updated: NOW,
    link: null,
    locked: false,
    frameId: null,
    seed: 3001,
    version: 1,
    versionNonce: 3001,
  } as AnyElement,
  {
    id: 'tmpl-flow-start-txt',
    type: 'text',
    x: -100,
    y: -248,
    width: 200,
    height: 30,
    angle: 0,
    strokeColor: '#2f9e44',
    backgroundColor: 'transparent',
    fillStyle: 'solid',
    strokeWidth: 1,
    strokeStyle: 'solid',
    roughness: 0,
    opacity: 100,
    groupIds: [],
    roundness: null,
    isDeleted: false,
    boundElements: [],
    updated: NOW,
    link: null,
    locked: false,
    frameId: null,
    seed: 3002,
    version: 1,
    versionNonce: 3002,
    text: 'Start',
    fontSize: 18,
    fontFamily: 1,
    textAlign: 'center',
    verticalAlign: 'middle',
    containerId: 'tmpl-flow-start',
    originalText: 'Start',
    lineHeight: 1.25,
    baseline: 16,
  } as AnyElement,
  // Step 1
  {
    id: 'tmpl-flow-step1',
    type: 'rectangle',
    x: -120,
    y: -140,
    width: 240,
    height: 60,
    angle: 0,
    strokeColor: '#1971c2',
    backgroundColor: '#d0ebff',
    fillStyle: 'solid',
    strokeWidth: 2,
    strokeStyle: 'solid',
    roughness: 0,
    opacity: 100,
    groupIds: [],
    roundness: { type: 3 },
    isDeleted: false,
    boundElements: [{ id: 'tmpl-flow-a1', type: 'arrow' }, { id: 'tmpl-flow-a2', type: 'arrow' }],
    updated: NOW,
    link: null,
    locked: false,
    frameId: null,
    seed: 3003,
    version: 1,
    versionNonce: 3003,
  } as AnyElement,
  {
    id: 'tmpl-flow-step1-txt',
    type: 'text',
    x: -120,
    y: -128,
    width: 240,
    height: 30,
    angle: 0,
    strokeColor: '#1971c2',
    backgroundColor: 'transparent',
    fillStyle: 'solid',
    strokeWidth: 1,
    strokeStyle: 'solid',
    roughness: 0,
    opacity: 100,
    groupIds: [],
    roundness: null,
    isDeleted: false,
    boundElements: [],
    updated: NOW,
    link: null,
    locked: false,
    frameId: null,
    seed: 3004,
    version: 1,
    versionNonce: 3004,
    text: 'Process Step 1',
    fontSize: 16,
    fontFamily: 1,
    textAlign: 'center',
    verticalAlign: 'middle',
    containerId: 'tmpl-flow-step1',
    originalText: 'Process Step 1',
    lineHeight: 1.25,
    baseline: 14,
  } as AnyElement,
  // Decision
  {
    id: 'tmpl-flow-decision',
    type: 'diamond',
    x: -100,
    y: -20,
    width: 200,
    height: 80,
    angle: 0,
    strokeColor: '#e67700',
    backgroundColor: '#fff3bf',
    fillStyle: 'solid',
    strokeWidth: 2,
    strokeStyle: 'solid',
    roughness: 0,
    opacity: 100,
    groupIds: [],
    roundness: { type: 3 },
    isDeleted: false,
    boundElements: [{ id: 'tmpl-flow-a2', type: 'arrow' }, { id: 'tmpl-flow-a3', type: 'arrow' }],
    updated: NOW,
    link: null,
    locked: false,
    frameId: null,
    seed: 3005,
    version: 1,
    versionNonce: 3005,
  } as AnyElement,
  {
    id: 'tmpl-flow-decision-txt',
    type: 'text',
    x: -100,
    y: 12,
    width: 200,
    height: 24,
    angle: 0,
    strokeColor: '#e67700',
    backgroundColor: 'transparent',
    fillStyle: 'solid',
    strokeWidth: 1,
    strokeStyle: 'solid',
    roughness: 0,
    opacity: 100,
    groupIds: [],
    roundness: null,
    isDeleted: false,
    boundElements: [],
    updated: NOW,
    link: null,
    locked: false,
    frameId: null,
    seed: 3006,
    version: 1,
    versionNonce: 3006,
    text: 'Decision?',
    fontSize: 15,
    fontFamily: 1,
    textAlign: 'center',
    verticalAlign: 'middle',
    containerId: 'tmpl-flow-decision',
    originalText: 'Decision?',
    lineHeight: 1.25,
    baseline: 13,
  } as AnyElement,
  // End
  {
    id: 'tmpl-flow-end',
    type: 'ellipse',
    x: -100,
    y: 120,
    width: 200,
    height: 60,
    angle: 0,
    strokeColor: '#c92a2a',
    backgroundColor: '#ffe3e3',
    fillStyle: 'solid',
    strokeWidth: 2,
    strokeStyle: 'solid',
    roughness: 0,
    opacity: 100,
    groupIds: [],
    roundness: null,
    isDeleted: false,
    boundElements: [{ id: 'tmpl-flow-a3', type: 'arrow' }],
    updated: NOW,
    link: null,
    locked: false,
    frameId: null,
    seed: 3007,
    version: 1,
    versionNonce: 3007,
  } as AnyElement,
  {
    id: 'tmpl-flow-end-txt',
    type: 'text',
    x: -100,
    y: 132,
    width: 200,
    height: 30,
    angle: 0,
    strokeColor: '#c92a2a',
    backgroundColor: 'transparent',
    fillStyle: 'solid',
    strokeWidth: 1,
    strokeStyle: 'solid',
    roughness: 0,
    opacity: 100,
    groupIds: [],
    roundness: null,
    isDeleted: false,
    boundElements: [],
    updated: NOW,
    link: null,
    locked: false,
    frameId: null,
    seed: 3008,
    version: 1,
    versionNonce: 3008,
    text: 'End',
    fontSize: 18,
    fontFamily: 1,
    textAlign: 'center',
    verticalAlign: 'middle',
    containerId: 'tmpl-flow-end',
    originalText: 'End',
    lineHeight: 1.25,
    baseline: 16,
  } as AnyElement,
  // Arrows
  {
    id: 'tmpl-flow-a1',
    type: 'arrow',
    x: 0,
    y: -200,
    width: 0,
    height: 60,
    angle: 0,
    strokeColor: '#495057',
    backgroundColor: 'transparent',
    fillStyle: 'solid',
    strokeWidth: 2,
    strokeStyle: 'solid',
    roughness: 0,
    opacity: 100,
    groupIds: [],
    roundness: { type: 2 },
    isDeleted: false,
    boundElements: [],
    updated: NOW,
    link: null,
    locked: false,
    frameId: null,
    seed: 3009,
    version: 1,
    versionNonce: 3009,
    points: [[0, 0], [0, 60]],
    lastCommittedPoint: null,
    startBinding: { elementId: 'tmpl-flow-start', focus: 0, gap: 1 },
    endBinding: { elementId: 'tmpl-flow-step1', focus: 0, gap: 1 },
    startArrowhead: null,
    endArrowhead: 'arrow',
  } as AnyElement,
  {
    id: 'tmpl-flow-a2',
    type: 'arrow',
    x: 0,
    y: -80,
    width: 0,
    height: 60,
    angle: 0,
    strokeColor: '#495057',
    backgroundColor: 'transparent',
    fillStyle: 'solid',
    strokeWidth: 2,
    strokeStyle: 'solid',
    roughness: 0,
    opacity: 100,
    groupIds: [],
    roundness: { type: 2 },
    isDeleted: false,
    boundElements: [],
    updated: NOW,
    link: null,
    locked: false,
    frameId: null,
    seed: 3010,
    version: 1,
    versionNonce: 3010,
    points: [[0, 0], [0, 60]],
    lastCommittedPoint: null,
    startBinding: { elementId: 'tmpl-flow-step1', focus: 0, gap: 1 },
    endBinding: { elementId: 'tmpl-flow-decision', focus: 0, gap: 1 },
    startArrowhead: null,
    endArrowhead: 'arrow',
  } as AnyElement,
  {
    id: 'tmpl-flow-a3',
    type: 'arrow',
    x: 0,
    y: 60,
    width: 0,
    height: 60,
    angle: 0,
    strokeColor: '#495057',
    backgroundColor: 'transparent',
    fillStyle: 'solid',
    strokeWidth: 2,
    strokeStyle: 'solid',
    roughness: 0,
    opacity: 100,
    groupIds: [],
    roundness: { type: 2 },
    isDeleted: false,
    boundElements: [],
    updated: NOW,
    link: null,
    locked: false,
    frameId: null,
    seed: 3011,
    version: 1,
    versionNonce: 3011,
    points: [[0, 0], [0, 60]],
    lastCommittedPoint: null,
    startBinding: { elementId: 'tmpl-flow-decision', focus: 0, gap: 1 },
    endBinding: { elementId: 'tmpl-flow-end', focus: 0, gap: 1 },
    startArrowhead: null,
    endArrowhead: 'arrow',
  } as AnyElement,
]

export interface WhiteboardTemplate {
  id: string
  name: string
  description: string
  emoji: string
  elements: AnyElement[]
}

export const TEMPLATES: WhiteboardTemplate[] = [
  {
    id: 'blank',
    name: 'Blank',
    description: 'Empty whiteboard',
    emoji: '⬜',
    elements: [],
  },
  {
    id: 'brainstorm',
    name: 'Sticky Notes',
    description: 'Grid of colour-coded sticky notes for brainstorming',
    emoji: '🗒️',
    elements: brainstormElements,
  },
  {
    id: 'flowchart',
    name: 'Flowchart',
    description: 'Start-process-decision-end flow diagram',
    emoji: '🔀',
    elements: flowchartElements,
  },
  {
    id: 'retro',
    name: 'Retrospective',
    description: 'Four-quadrant agile retrospective board',
    emoji: '🔁',
    elements: retroElements,
  },
]
